baby02:
	nasm baby02.asm -f bin -o baby02.bin
	qemu-system-i386 -fda baby02.bin

baby02_procedure:
	nasm baby02_procedure.asm -f bin -o baby02_procedure.bin
	qemu-system-i386 -fda baby02_procedure.bin
