baby04:
	nasm baby04.asm -f bin -o baby04.bin
	qemu-system-i386 -hda baby04.bin

baby04_more_chars:
	nasm baby04_more_chars.asm -f bin -o baby04_more_chars.bin
	qemu-system-i386 -hda baby04_more_chars.bin
